INSERT INTO user (id, username, password, role, created_at) VALUES(1, 'admin', '$2b$12$dTkw6z/oIiL8E7J8HzwMs.AdshfaJjBsyq1w53waZvfhwH0Wu0n4C', 'ADMIN', DATE('now'));
INSERT INTO user (id, username, password, role, created_at) VALUES(2, 'tuser1', '$2b$12$KDOUfDo.1eO3WEb2/PM.Bu7oaay6kmbXqEfJs7rRyMAqTABSuYyjO', 'USER', DATE('now'));
INSERT INTO user (id, username, password, role, created_at) VALUES(3, 'tuser2', '$2b$12$KDOUfDo.1eO3WEb2/PM.Bu7oaay6kmbXqEfJs7rRyMAqTABSuYyjO', 'USER', DATE('now'));
INSERT INTO user (id, username, password, role, created_at) VALUES(4, 'tuser3', '$2b$12$KDOUfDo.1eO3WEb2/PM.Bu7oaay6kmbXqEfJs7rRyMAqTABSuYyjO', 'USER', DATE('now'));
INSERT INTO user (id, username, password, role, created_at) VALUES(5, 'towner1', '$2b$12$KDOUfDo.1eO3WEb2/PM.Bu7oaay6kmbXqEfJs7rRyMAqTABSuYyjO', 'OWNER', DATE('now'));
INSERT INTO user (id, username, password, role, created_at) VALUES(6, 'towner2', '$2b$12$KDOUfDo.1eO3WEb2/PM.Bu7oaay6kmbXqEfJs7rRyMAqTABSuYyjO', 'OWNER', DATE('now'));
INSERT INTO user (id, username, password, role, created_at) VALUES(7, 'tuser4', '$2b$12$KDOUfDo.1eO3WEb2/PM.Bu7oaay6kmbXqEfJs7rRyMAqTABSuYyjO', 'USER', DATE('now'));
INSERT INTO category VALUES (1, 'Primary 1', 1);
INSERT INTO category VALUES (2, 'Primary 2', 1);
INSERT INTO category VALUES (3, 'Secondary 1', 0);
INSERT INTO category VALUES (4, 'Secondary 2', 0);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant_item VALUES (1, "Test Item 1", null, "Test Item Description", 1.05, 1);
INSERT INTO restaurant_item VALUES (2, "Test Item 2", null, "Test Item Description 2", 1.05, 1);
INSERT INTO restaurant_item VALUES (3, "Test Item 3", null, "Test Item Description 3", 1.99, 1);
INSERT INTO restaurant_item VALUES (4, "Test Item 4", null, "Test Item Description 4", 1.98, 1);
INSERT INTO restaurant_item VALUES (5, "Test Item 5", null, "Test Item Description 5", 1.97, 1);
INSERT INTO restaurant_item VALUES (6, "Test Item 6", null, "Test Item Description 6", 1.96, 1);
INSERT INTO restaurant_item VALUES (7, "Test Item 7", null, "Test Item Description 7", 1.95, 1);
INSERT INTO cart VALUES (1, 0, null, 1, 2);
INSERT INTO cart_item VALUES (1, 1, 1, 1);
INSERT INTO cart_item VALUES (2, 2, 1, 2);
INSERT INTO restaurant ('name', 'description', 'image', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 2', 'Test Restaurant Description', '2b8370dbb768ece35cc826d2a6c4682c' ,DATE('now'), DATE('now'), 5);
INSERT INTO restaurant_item VALUES (8, "Test Item 2-1", null, "Test Item Description 2-1", 1.98, 2);
INSERT INTO restaurant_item VALUES (9, "Test Item 2-2", null, "Test Item Description 2-2", 1.97, 2);
INSERT INTO restaurant_item VALUES (10, "Test Item 2-3", null, "Test Item Description 2-3", 1.96, 2);
INSERT INTO restaurant_item VALUES (11, "Test Item 2-4", null, "Test Item Description 2-4", 1.95, 2);
INSERT INTO restaurant_item VALUES (12, "Test Item 2-5", null, "Test Item Description 2-5", 1.94, 2);
INSERT INTO restaurant_item VALUES (13, "Test Item 2-6", null, "Test Item Description 2-6", 1.93, 2);
INSERT INTO restaurant_item VALUES (14, "Test Item 2-7", null, "Test Item Description 2-7", 1.92, 2);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 3', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant_item VALUES (15, "Test Item 3-1", null, "Test Item Description 3-1", 2.98, 3);
INSERT INTO restaurant_item VALUES (16, "Test Item 3-2", null, "Test Item Description 3-2", 2.97, 3);
INSERT INTO restaurant_item VALUES (17, "Test Item 3-3", null, "Test Item Description 3-3", 2.96, 3);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 4', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 5', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 6', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 7', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 8', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 9', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 10', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 11', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 12', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 13', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 14', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 15', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 16', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 17', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 18', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 19', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 20', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 21', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 22', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 23', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 24', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 25', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 26', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 27', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 28', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 29', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 30', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 31', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 32', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 33', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 34', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 35', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 36', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 37', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 38', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 39', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 40', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 41', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 42', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 43', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 44', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 45', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 46', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant ('name', 'description', 'created_at', 'modified_at', 'owner_id') VALUES ('Test Restaurant 47', 'Test Restaurant Description', DATE('now'), DATE('now'), 5);
INSERT INTO restaurant_categories ('restaurant_id', 'category_id') VALUES (1, 1);
INSERT INTO restaurant_categories ('restaurant_id', 'category_id') VALUES (1, 2);
INSERT INTO restaurant_categories ('restaurant_id', 'category_id') VALUES (1, 3);
INSERT INTO restaurant_categories ('restaurant_id', 'category_id') VALUES (1, 4);
INSERT INTO restaurant_categories ('restaurant_id', 'category_id') VALUES (2, 1);
INSERT INTO restaurant_categories ('restaurant_id', 'category_id') VALUES (2, 3);
