name: CI

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  frontend:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: food-delivery-client
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache-dependency-path: food-delivery-client/package-lock.json
      - name: Install dependencies
        run: npm i
      - run: npm run build --if-present
      - name: Run tests
        run: npm run test