name: CI

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  frontend:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: food-delivery-client
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache-dependency-path: food-delivery-client/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Start
        run: npm run start &